DROP TABLE BOARD;

CREATE TABLE BOARD(
		NO               INT				NOT NULL	PRIMARY KEY AUTO_INCREMENT,
		TITLE            VARCHAR(30)		NOT NULL,
		CONTENT          VARCHAR(255)		NULL,
		WRITER           VARCHAR(10)		NOT NULL,
		REGDATE          DATE			 	NOT NULL,
		MODIDATE		 DATE				NULL
);

